name: monarch-mcp
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pytest>=7.0.0
  - pytest-asyncio>=0.21.0
  - openai
  - python-dotenv
  - pip:
    - mcp>=1.0.0
    - aiohttp>=3.9.0
    - pydantic>=2.0.0
    - -e .